language: cpp

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
#    - os: osx
#      osx_image: xcode9.3

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - sourceline: 'ppa:cginternals/backports-ppa'
    packages:
      - gcc-7
      - g++-7
      - build-essential
      - autoconf
      - automake
      - bison
      - flex
      - libncurses5-dev
      - libreadline-dev
      - texinfo
      - pkg-config
      - libgmp-dev
      - libmpfr-dev
      - libmpc-dev

cache:
  directories:
    - "$HOME/.local"

git:
  submodules: true

install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-7 90; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-7 90; fi

script:
  - cd "$TRAVIS_BUILD_DIR"
  - travis_wait 30 bash build-devkit.sh
